#!/bin/ash
export TEXTDOMAIN=orange
export OUTPUT_CHARSET=UTF-8

#pkg-name
PN=avidemux
#executable-name
EN=avidemux
#real-name
RN="Avidemux"
#alt-exe-names
AN=""
#short-descr
SD="Video editor"
#homepage
HP="https://avidemux.sourceforge.net/"
#mini-icon (found in /usr/local/lib/X11/mini-icons)
MI=mini-Multimedia-audiovideo
#run app as this user ***FUTURE*** currently only recognize root
UN=avidemux
#post-install frame...
PF=""
