#!/bin/ash
export TEXTDOMAIN=orange
export OUTPUT_CHARSET=UTF-8

#pkg-name
PN=dia
#executable-name
EN=dia
#real-name
RN="Dia"
#alt-exe-names
AN=""
#short-descr
SD="Diagram editor"
#homepage
HP="https://wiki.gnome.org/Apps/Dia/"
#mini-icon (found in /usr/local/lib/X11/mini-icons)
MI=mini-Document-layout
#run app as this user ***FUTURE*** currently only recognize root
UN=dia
#post-install frame...
PF=""
