#!/bin/ash
export TEXTDOMAIN=orange
export OUTPUT_CHARSET=UTF-8

#pkg-name
PN=obs
PNalt="obs-studio" #devuan
#executable-name
EN=obs
#real-name
RN="OBS-Studio"
#alt-exe-names
AN=""
#short-descr
SD="Video streaming/recording"
#homepage
HP="https://obsproject.com/"
#mini-icon (found in /usr/local/lib/X11/mini-icons)
MI=mini-Multimedia-audiovideo
#run app as this user ***FUTURE*** currently only recognize root
UN=obs
#post-install frame...
PF=""
