#!/bin/ash
export TEXTDOMAIN=orange
export OUTPUT_CHARSET=UTF-8

#pkg-name
PN=scribus
#executable-name
EN=scribus
#real-name
RN="Scribus"
#alt-exe-names
AN=""
#short-descr
SD="Desktop publishing"
#homepage
HP="https://www.scribus.net/"
#mini-icon (found in /usr/local/lib/X11/mini-icons)
MI=mini-Document-layout
#run app as this user ***FUTURE*** currently only recognize root
UN=scribus
#post-install frame...
PF=""
