#!/bin/ash
export TEXTDOMAIN=orange
export OUTPUT_CHARSET=UTF-8

#pkg-name
PN=vlc
#executable-name
EN=vlc
#real-name
RN="VLC"
#alt-exe-names
AN=""
#short-descr
SD="Media player"
#homepage
HP="https://www.videolan.org/vlc/"
#mini-icon (found in /usr/local/lib/X11/mini-icons)
MI=mini-Multimedia-mediaplayer
#run app as this user ***FUTURE*** currently only recognize root
UN=vlc
#post-install frame...
PF=""
