#!/bin/ash
export TEXTDOMAIN=orange
export OUTPUT_CHARSET=UTF-8

#pkg-name
PN=vym
#executable-name
EN=vym
#real-name
RN="VYM"
#alt-exe-names
AN=""
#short-descr
SD="Mind mapper"
#homepage
HP="https://www.insilmaril.de/vym/"
#mini-icon (found in /usr/local/lib/X11/mini-icons)
MI=mini-Personal-organizer
#run app as this user ***FUTURE*** currently only recognize root
UN=vym
#post-install frame...
PF=""
