#!/bin/ash
#called from limine-installer
#find-installations has created /tmp/limine-installer/unique-check-usb.log
#and /tmp/limine-installer/unique-check-internal.log
#20230103

export TEXTDOMAIN=limine-installer
export TEXTDOMAINDIR=/usr/share/locale
export OUTPUT_CHARSET=UTF-8

echo -n '' > /tmp/limine-installer/conflicts-found

if [ ! -s /tmp/limine-installer/unique-check-internal.log ];then
 exit 0
fi

#ex: KNAME="sda8" LABEL="hdd96gb1" UUID="aad57b63-14e1-4fd5-ac01-14d15ef81e3e" PARTUUID="1911d005-c4cb-4f06-8975-208d32755084"

DUPS="$(cat /tmp/limine-installer/unique-check-internal.log /tmp/limine-installer/unique-check-usb.log | tr ' ' '\n' | cut -f 2 -d '"' | sort | uniq -d)"

if [ "$DUPS" ];then
 for aDUP in `echo -n "${DUPS}" | tr '\n' ' '`
 do
  aTYPE="$(cat /tmp/limine-installer/unique-check-internal.log /tmp/limine-installer/unique-check-usb.log | tr ' ' '\n' | grep "\"${aDUP}\"" | head -n 1)"
  PARTSint="$(grep "\"${aDUP}\"" /tmp/limine-installer/unique-check-internal.log | cut -f 2 -d '"')"
  PARTSusb="$(grep "\"${aDUP}\"" /tmp/limine-installer/unique-check-usb.log | cut -f 2 -d '"')"
  echo "
Duplicates: ${aTYPE}" >> /tmp/limine-installer/conflicts-found
  if [ "PARTSint" ];then
   xP="$(echo -n "$PARTSint" | tr '\n' ' ')"
   echo "Internal Partitions: ${xP}" >> /tmp/limine-installer/conflicts-found
  fi
  if [ "PARTSusb" ];then
   xP="$(echo -n "$PARTSusb" | tr '\n' ' ')"
   echo "USB Partitions: ${xP}" >> /tmp/limine-installer/conflicts-found
  fi
 done
fi

if [ -s /tmp/limine-installer/conflicts-found ];then
 xC="$(cat /tmp/limine-installer/conflicts-found | tr '"' "'")"
 xD="$(gettext "If limine.cfg has one of these parameters, Limine will be confused if it finds the parameter in more than one partition.")"
 xE="$(gettext "You may continue, but you must remove the conflict before booting with Limine bootloader. If the conflict is on a USB drive, remove it before booting with Limine installed to an internal drive.")"
 xF="$(gettext "Note: Gparted may be used to change the UUID and label of any partition.")"
 export LI_CONFLICT_DLG="<window title=\"$(gettext 'LimineInstaller: conflicts found')\" image-name=\"/usr/share/pixmaps/limine-installer.png\" window_position=\"1\">
 <vbox>
  <text use-markup=\"true\"><label>\"<b>$(gettext 'WARNING, conflicting partition parameters')</b>\"</label></text>
  <text><label>\"${xC}\"</label></text>
  <text><label>\"  \"</label></text>
  <text><label>${xD}</label></text>
  <text><label>${xE}</label></text>
  <text><label>${xF}</label></text>
  <hbox>
   <button>
    <label>$(gettext 'CONTINUE')</label>
    <action>exit:continue</action>
   </button>
   <button cancel></button>
  </hbox>
 </vbox>
</window>"
 echo "$LI_CONFLICT_DLG" > /tmp/limine-installer/LI_CONFLICT_DLG #debug
 VARSc="$(gtkdialog --program=LI_CONFLICT_DLG)"
 echo "${VARSc}" > /tmp/limine-installer/VARSc
 
 grep -q 'continue' /tmp/limine-installer/VARSc
 if [ $? -ne 0 ];then
  exit 1
 fi
fi
exit 0
###end###
