#!/bin/ash
#called from 3populate-rootfs
#$1 is folder already usrmerge, but symlinks may be broken.
#ex: this can happen with busybox pet, after applying symlinks-fix script.
#simplify the symlinks. also detect circular symlinks.

#expect to be in same path as $F2
F2="$1"
if [ ! -d "$F2" ];then
 echo "ERROR: symlinks-fix: folder does not exist"
 exit 1
fi

while read aL
do
 [ ! "$aL" ] && continue
 LANG=C busybox realpath ${aL} 2>&1 | grep -q 'Symbolic link loop'
 if [ $? -eq 0 ];then
  rm -f ${F2}/usr/bin/${aL##*/} #delete circular loop.
  continue
 fi
 aT="$(busybox readlink -n $aL)"
 if [ -f ${F2}/usr/bin/${aT##*/} ];then
  if [ ! -h ${F2}/usr/bin/${aT##*/} ];then
   ln -snf ${aT##*/} ${aL} #simplify symlink.
  fi
 fi
done <<_END2
$(find ${F2}/usr/bin -mindepth 1 -maxdepth 1 -type l 2>/dev/null)
_END2

while read aL
do
 [ ! "$aL" ] && continue
 LANG=C busybox realpath ${aL} 2>&1 | grep -q 'Symbolic link loop'
 if [ $? -eq 0 ];then
  rm -f ${F2}/usr/lib/${aL##*/} #delete circular loop.
  continue
 fi
 aT="$(busybox readlink -n $aL)"
 if [ -f ${F2}/usr/lib/${aT##*/} ];then
  if [ ! -h ${F2}/usr/lib/${aT##*/} ];then
   ln -snf ${aT##*/} ${aL}
  fi
 fi
done <<_END2
$(find ${F2}/usr/lib -mindepth 1 -maxdepth 1 -type l 2>/dev/null)
_END2

###end###
