user_pref("browser.startup.homepage_override.mstone", "ignore");
user_pref("browser.tabs.warnOnClose", false);
user_pref("layers.acceleration.disabled", true);
user_pref("startup.homepage_override_url","about:blank");
user_pref("startup.homepage_welcome_url","about:blank");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("app.update.auto", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("media.videocontrols.picture-in-picture.video-toggle.enabled", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("widget.non-native-theme.gtk.scrollbar.allow-buttons", true);
user_pref("browser.cache.disk.capacity", 64000);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.download.dir", "/files");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.tabs.forceHide", true);
user_pref("browser.chrome.toolbar_style", 0);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.startup.homepage", "about:blank");
