#!/bin/sh
#when want to do a quick reconstruction of the iso from the 'build' dir.
#note: efiboot.img has another 'initrd' inside it, for efi booting.

cd sandbox4
[ ! -f build/efiboot.img ] && exit 1
. ../DISTRO_SPECS

ISONAME="easypup-${DISTRO_VERSION}-test.iso"
[ -f ${ISONAME} ] && mv -f ${ISONAME} ${ISONAME}BAK

 xorriso -as mkisofs -volid "EASYPUPOPTICAL" -o ${ISONAME} -isohybrid-mbr isohdpfx.bin \
   -c boot.cat -b isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table \
   -eltorito-alt-boot -e efiboot.img -no-emul-boot -isohybrid-gpt-basdat ./build/
sync
echo
echo "${ISONAME} has been created."
