#!/bin/bash

export TEXTDOMAIN=flatpaks
export TEXTDOMAINDIR=/usr/share/locale
export OUTPUT_CHARSET=UTF-8

ENTRIESaudio="
<item icon-name=\"audacity\">Audacity|${FLGaudacity}|$(gettext 'A free, easy-to-use, multi-track audio editor and recorder')</item>
<item icon-name=\"cozy\">Cozy|${FLGcozy}|$(gettext 'Audio book player')</item>
<item icon-name=\"tuner\">Tuner|${FLGtuner}|$(gettext 'Listen to Internet radio stations')</item>
"
echo "$ENTRIESaudio" > /tmp/flatpak/ENTRIESaudio

ENTRIESdeveloper="
<item icon-name=\"androidstudio\">AndroidStudio|${FLGandroidstudio}|$(gettext 'IDE for Android app development')</item>
<item icon-name=\"cambalache\">Cambalache|${FLGcambalache}|$(gettext 'GTK3 and GTK4 interface designer')</item>
<item icon-name=\"diylc\">DIYLC|${FLGdiylc}|$(gettext 'Electrical and electronic circuit board layout designer')</item>
<item icon-name=\"gdevelop\">GDevelop|${FLGgdevelop}|$(gettext 'No-code game development')</item>
<item icon-name=\"purrdata\">PurrData|${FLGpurrdata}|$(gettext 'Visual programming environment')</item>
<item icon-name=\"scratch\">Scratch|${FLGscratch}|$(gettext 'Simple GUI app creator')</item>
<item icon-name=\"smartgit\">SmartGit|${FLGsmartgit}|$(gettext 'Git and SVN client. No.1 rating at slant.co')</item>
<item icon-name=\"vscode\">VSCode|${FLGvscode}|$(gettext 'Visual Studio Code editor')</item>
"
echo "$ENTRIESdeveloper" > /tmp/flatpak/ENTRIESdeveloper

ENTRIESgames="
<item icon-name=\"frogatto\">Frogatto|${FLGfrogatto}|$(gettext '2D adventure game')</item>
<item icon-name=\"ppsspp\">PPSSPP|${FLGppsspp}|$(gettext 'PlayStation PSP emulator')</item>
"
echo "$ENTRIESgames" > /tmp/flatpak/ENTRIESgames

ENTRIESgraphics="
<item icon-name=\"krita\">Krita|${FLGkrita}|$(gettext 'Vector and raster painting program')</item>
"
echo "$ENTRIESgraphics" > /tmp/flatpak/ENTRIESgraphics

ENTRIESnetwork="
<item icon-name=\"betterbird\">Betterbird|${FLGbetterbird}|$(gettext 'Fork of Mozilla Thunderbird mail client')</item>
<item icon-name=\"fragments\">Fragments|${FLGfragments}|$(gettext 'A BitTorrent client')</item>
<item icon-name=\"jitsimeet\">JitsiMeet|${FLGjitsimeet}|$(gettext 'Video conferencing')</item>
<item icon-name=\"teams\">Teams|${FLGteams}|$(gettext 'Microsoft Teams client')</item>
"
echo "$ENTRIESnetwork" > /tmp/flatpak/ENTRIESnetwork

ENTRIESoffice="
<item icon-name=\"calibre\">Calibre|${FLGcalibre}|$(gettext 'E-book reader')</item>
<item icon-name=\"okular\">Okular|${FLGokular}|$(gettext 'Universal document viewer')</item>
"
echo "$ENTRIESoffice" > /tmp/flatpak/ENTRIESoffice

ENTRIESproductivity="
<item icon-name=\"authpass\">AuthPass|${FLGauthpass}|$(gettext 'Password manager')</item>
<item icon-name=\"identity\">Identity|${FLGidentity}|$(gettext 'Compare multiple versions of an image or video')</item>
<item icon-name=\"minder\">Minder|${FLGminder}|$(gettext 'Mind-mapping ideas visualization tool')</item>
<item icon-name=\"trilium\">Trilium|${FLGtrilium}|$(gettext 'Hierarchical note-taking and personal database')</item>
"
echo "$ENTRIESproductivity" > /tmp/flatpak/ENTRIESproductivity

ENTRIESsystem="
<item icon-name=\"dosbox\">DOSBox|${FLGdosbox}|$(gettext 'DOS emulator')</item>
"
echo "$ENTRIESsystem" > /tmp/flatpak/ENTRIESsystem

ENTRIESvideo="
<item icon-name=\"kdenlive\">Kdenlive|${FLGkdenlive}|$(gettext 'Nonlinear video editor')</item>
<item icon-name=\"obs\">OBS|${FLGobs}|$(gettext 'OBS-Studio video capture, recording and live streaming')</item>
<item icon-name=\"openshot\">OpenShot|${FLGopenshot}|$(gettext 'Easy and powerful video editor')</item>
"
echo "$ENTRIESvideo" > /tmp/flatpak/ENTRIESvideo

ENTRIESother="
<item icon-name=\"gramps\">Gramps|${FLGgramps}|$(gettext 'Genealogy program')</item>
<item icon-name=\"organicmaps\">OrganicMaps|${FLGorganicmaps}|$(gettext 'Offline maps for travellers, hikers and cyclists')</item>
<item icon-name=\"qgis\">QGIS|${FLGqgis}|$(gettext 'Open source Geographic Information System')</item>
"
echo "$ENTRIESother" > /tmp/flatpak/ENTRIESother

###end###
