#!/bin/sh
#have replaced pup_event_frontend_d script with compiled daemon.
#this script is called from /root/.xinitrc
#20221023 may be running as zeus super-user. 20221031 think still need to bump to root.

WHOIAM="$(whoami)"
[ "${WHOIAM}" != "root" ] && exec sudo -A ${0} ${@} #20221023 20221031

exec /usr/local/pup_event/pup_event_frontend_d

###END###
