#!/bin/bash
#d/l and install an appimage.

export TEXTDOMAIN=appimages
export TEXTDOMAINDIR=/usr/share/locale
export OUTPUT_CHARSET=UTF-8

CR='
'
mkdir -p /tmp/appimage

H_appimg="$(gettext 'AppImages are applications that contain all dependencies built-in, so they will run on almost any Linux distribution, without having to install any other packages.')
$(gettext 'Consequently, they are large, typically 50MB to 900MB, so you do need reasonably fast Internet and adequate data allowance with your telco.')

$(gettext 'The Appimages are installed so that each runs as its own user, which maximizes isolation and hence security. However, there is the option of running them as the root user.')

$(gettext 'Upon installation, a menu-entry is created, and you are good-to-go.')

<b>$(gettext 'Notes')</b>
$(gettext 'A tick in the second column means that the AppImage is already installed. You may then have the opportunity of updating or deleting it.')
$(gettext 'After an AppImage is installed, the file-manager will recognize the file types handled by that app. Right-click on an appropriate file and the AppImage will be offered to open it.')
$(gettext 'If you entered a password at first bootup of EasyOS, then all working folders are encrypted, and this includes files created by the AppImage while you are using it. If your USB-stick, or on whatever media EasyOS is installed, is stolen, your data is safe.')"
export DLG_HELP_APPIMG="<window resizable=\"false\" title=\"$(gettext 'Help: AppImage Installer')\" icon-name=\"gtk-index\" window_position=\"1\"><vbox><text use-markup=\"true\"><label>\"${H_appimg}\"</label><variable>DLG_HELP_APPIMG</variable></text><hbox><button><label>$(gettext 'Close')</label><action type=\"closewindow\">DLG_HELP_APPIMG</action></button></hbox></vbox></window>"

#does not work, due to internal libs requiring a later glibc:
#        <item icon-name=\"cozydrive\">CozyDrive|$(gettext 'Synchronize files with laptop and desktop PC')</item>
#get splash window, then aborts:
#        <item icon-name=\"shotcut\">ShotCut|${FLGshotcut}|$(gettext 'Easy and powerful video editor')</item>
#missing python module:
#        <item icon-name=\"vidcutter\">VidCutter|${FLGvidcutter}|$(gettext 'A simple video cutter and joiner')</item>
#/usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full :
#        <item icon-name=\"emacs\">Emacs|${FLGemacs}|$(gettext 'GNU Emacs text editor')</item>
#FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.:
#        <item icon-name=\"circuitblocks\">CircuitBlocks|${FLGcircuitblocks}|$(gettext 'Graphical coding for Arduino using Google Blockly')</item>
#terminate called after throwing an instance of 'std::logic_error'
#  what():  basic_string: construction from null is not valid :
#        <item icon-name=\"imhex\">ImHex|${FLGimhex}|$(gettext 'Hex editor for reverse engineers')</item>
#./bin/kicad: /usr/lib/libcrypt.so.1: version `GLIBC_2.2.5' not found (required by /tmp/.mount_kicad.Ru9zq7/usr/lib/x86_64-linux-gnu/libkrb5.so.26)
#./bin/kicad: /usr/lib/libcrypt.so.1: version `GLIBC_2.2.5' not found (required by /tmp/.mount_kicad.Ru9zq7/usr/lib/x86_64-linux-gnu/libroken.so.18)
#        <item icon-name=\"kicad\">KiCad|${FLGkicad}|$(gettext 'Schematic-capture and PCB layout designer')</item>

#took this out of System tab, as these are untested, over half don't work:
#        <item icon-name=\"appimagepool\">AppImagePool|${FLGappimagepool}|$(gettext 'AppImageHub AppImage installer')</item>


#find out what already installed...
for aAI in $(find /mnt/wkg/appimage -mindepth 1 -maxdepth 1 -type d)
do
 [ "$aAI" == "" ] && continue
 AIfile="$(find ${aAI} -mindepth 1 -maxdepth 1 -type f -name '*.AppImage' | tail -n 1)"
 if [ "$AIfile" ];then
  #.AppImage may have been manually downloaded, so check if actually installed...
  if [ -x /usr/bin/${aAI##*/} ];then
   eval "FLG${aAI##*/}='√'" #ex: sets FLGaudacity=√
  fi
 else
  #remove .specs file, if it exists...
  rm -f ${aAI}/${aAI##*/}.specs 2>/dev/null
  #remove symlink to appimage, if it exists...
  rm -f ${aAI}/${aAI##*/}.bin 2>/dev/null
 fi
done

PACKAGE="AppImage"
DESCRIPTION="$(gettext 'Description')"
SIZE="$(gettext 'Size')"
export APPIMG_DLG1="<window title=\"$(gettext 'AppImage Installer')\">
  <vbox>
    <text use-markup=\"true\"><label>\"$(gettext 'AppImages are applications with all dependencies builtin.')${CR}$(gettext 'They may be downloaded and installed in EasyOS.')${CR}$(gettext 'An existing installation may be updated or deleted.')\"</label></text>
    <notebook labels=\"$(gettext 'Audio')|$(gettext 'Developer')|$(gettext 'Games')|$(gettext 'Graphics')|$(gettext 'Network')|$(gettext 'Office')|$(gettext 'Productivity')|$(gettext 'System')|$(gettext 'Video')|$(gettext 'Other')\">
      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEaudio</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEaudio</action>
        <item icon-name=\"audacity\">Audacity|${FLGaudacity}|44M|$(gettext 'A free, easy-to-use, multi-track audio editor and recorder')</item>
      </tree>
      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEdeveloper</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEdeveloper</action>
        <item icon-name=\"figma\">Figma|${FLGfigma}|102M|$(gettext 'User Interface design tool')</item>
        <item icon-name=\"gdevelop\">GDevelop|${FLGgdevelop}|128M|$(gettext 'No-code game creation')</item>
        <item icon-name=\"gitqlient\">GitQlient|${FLGgitqlient}|28M|$(gettext 'Multi-platform GIT client written with Qt')</item>
        <item icon-name=\"glyphr\">Glyphr|${FLGglyphr}|110M|$(gettext 'Web-based font designer')</item>
        <item icon-name=\"guitar\">Guitar|${FLGguitar}|21M|$(gettext 'GIT GUI client')</item>
        <item icon-name=\"insight\">Insight|${FLGinsight}|110M|$(gettext 'GUI frontend for GNU Debugger')</item>
      </tree>
      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEgames</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEgames</action>
        <item icon-name=\"cromagrally\">CroMagRally|${FLGcromagrally}|129M|$(gettext 'Cro-Magnon car racing game')</item>
        <item icon-name=\"endlesssky\">EndlessSky|${FLGendlesssky}|232M|$(gettext 'Outer-space adventure game')</item>
        <item icon-name=\"nanosaur\">Nanosaur|${FLGnanosaur}|17M|$(gettext 'Strategy 3D game')</item>
        <item icon-name=\"ottomatic\">OttoMatic|${FLGottomatic}|141M|$(gettext 'Strategy 3D game')</item>
        <item icon-name=\"planetblupi\">PlanetBlupi|${FLGplanetblupi}|105M|$(gettext 'Strategy and adventure game')</item>
      </tree>
      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEgraphics</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEgraphics</action>
        <item icon-name=\"digikam\">digiKam|${FLGdigikam}|240M|$(gettext 'Professional photo manager')</item>
        <item icon-name=\"dust3d\">Dust3D|${FLGdust3d}|25M|$(gettext '3D modeling')</item>
        <item icon-name=\"freecad\">FreeCAD|${FLGfreecad}|944M|$(gettext '3D parametric modeling')</item>
        <item icon-name=\"krita\">Krita|${FLGkrita}|334M|$(gettext 'Vector and raster painting program')</item>
        <item icon-name=\"librecad\">LibreCAD|${FLGlibrecad}|47M|$(gettext '2D CAD')</item>
        <item icon-name=\"mypaint\">MyPaint|${FLGmypaint}|46M|$(gettext 'Paint program, excellent with graphics tablet')</item>
        <item icon-name=\"openscad\">OpenSCAD|${FLGopenscad}|39M|$(gettext 'Solid 3D CAD modeller')</item>
        <item icon-name=\"pdfquirk\">PDFQuirk|${FLGpdfquirk}|18M|$(gettext 'Convert images to PDF')</item>
        <item icon-name=\"phototool\">PhotoTool|${FLGphototool}|30M|$(gettext 'Photo editor')</item>
      </tree>
      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEnetwork</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEnetwork</action>
        <item icon-name=\"altus\">Altus|${FLGaltus}|95M|$(gettext 'WhatsApp messaging and calls')</item>
        <item icon-name=\"electorrent\">Electorrent|${FLGelectorrent}|82M|$(gettext 'A client for uTorrent, rTorrent, Transmission, etc.')</item>
        <item icon-name=\"jitsimeet\">JitsiMeet|${FLGjitsimeet}|90M|$(gettext 'Online video conferencing')</item>
        <item icon-name=\"keepassxc\">KeePassXC|${FLGkeepassxc}|40M|$(gettext 'Password manager')</item>
        <item icon-name=\"telegram\">Telegram|${FLGtelegram}|50M|$(gettext 'Simple, fast, secure messaging')</item>
        <item icon-name=\"thunderbird\">Thunderbird|${FLGthunderbird}|82M|$(gettext 'Mozilla mail client')</item>
        <item icon-name=\"ungoogledchromium\">UngoogledChromium|${FLGungoogledchromium}|149M|$(gettext 'Chromium browser without Google Services')</item>
        <item icon-name=\"zoom\">Zoom|${FLGzoom}|227M|$(gettext 'Online video conferencing')</item>
      </tree>
      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEoffice</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEoffice</action>
        <item icon-name=\"antares\">Antares|${FLGantares}|126M|$(gettext 'SQL client')</item>
        <item icon-name=\"dbbrowser\">DBBrowser|${FLGdbbrowser}|37M|$(gettext 'Create and edit SQLITE databases')</item>
        <item icon-name=\"dbgate\">DbGate|${FLGdbgate}|93M|$(gettext 'Multi-protocol SQL+noSQL database client')</item>
        <item icon-name=\"koodoreader\">KoodoReader|${FLGkoodoreader}|87M|$(gettext 'Multi-format e-book reader')</item>
        <item icon-name=\"koreader\">KOReader|${FLGkoreader}|42M|$(gettext 'Multi-format e-book reader')</item>
        <item icon-name=\"onlyoffice\">ONLYOFFICE|${FLGonlyoffice}|299M|$(gettext 'Word-processing, spreadsheet, presentations office suite')</item>
      </tree>
      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEproductivity</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEproductivity</action>
        <item icon-name=\"acreom\">Acreom|${FLGacreom}|174M|$(gettext 'Private knowledge base')</item>
        <item icon-name=\"deltachat\">DeltaChat|${FLGdeltachat}|143M|$(gettext 'Desktop and phone messaging app')</item>
        <item icon-name=\"goldendict\">GoldenDict|${FLGgoldendict}|56M|$(gettext 'Feature-rich dictionary lookup')</item>
        <item icon-name=\"groot\">Groot|${FLGgroot}|42M|$(gettext 'BehaviorTree diagram creator')</item>
        <item icon-name=\"heimer\">Heimer|${FLGheimer}|25M|$(gettext 'Mind mapping diagrammer tool')</item>
        <item icon-name=\"onenote\">OneNote|${FLGonenote}|93M|$(gettext 'A Linux version of Microsoft OneNote')</item>
      </tree>
      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEsystem</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEvideo</action>
        <item icon-name=\"etcher\">Etcher|${FLGetcher}|98M|$(gettext 'Flash OS images to SD and USB drives')</item>
      </tree>

      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEvideo</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEvideo</action>
        <item icon-name=\"kdenlive\">Kdenlive|${FLGkdenlive}|175M|$(gettext 'Video editor')</item>
        <item icon-name=\"losslesscut\">LosslessCut|${FLGlosslesscut}|153M|$(gettext 'Video editor')</item>
        <item icon-name=\"openshot\">OpenShot|${FLGopenshot}|229M|$(gettext 'Easy and powerful video editor')</item>
        <item icon-name=\"webcamoid\">Webcamoid|${FLGwebcamoid}|86M|$(gettext 'A full-featured webcam suite')</item>
      </tree>

      <tree column-resizeable=\"0\">
        <label>${PACKAGE}||${SIZE}|${DESCRIPTION}</label>
        <height>300</height>
        <variable>TREEother</variable>
        <action signal=\"enter-notify-event\" type=\"refresh\">TREEother</action>
        <item icon-name=\"exelearning\">eXeLearning|${FLGexelearning}|97M|$(gettext 'Create educational resources')</item>
        <item icon-name=\"leocad\">LeoCAD|${FLGleocad}|125M|$(gettext 'Build models with lego bricks')</item>
      </tree>

    </notebook>
    <hbox>
      <text><label>$(gettext 'Highlight an AppImage then click a button:')</label></text>
      <text><label>\"  \"</label></text>
    </hbox>
    <hbox>
      <button space-expand=\"false\" space-fill=\"false\"><input file>/usr/local/lib/X11/mini-icons/mini-question.xpm</input><action type=\"launch\">DLG_HELP_APPIMG</action></button>
      <button space-expand=\"false\" space-fill=\"false\"><label>$(gettext 'Exit')</label><action>exit:QUIT</action></button>
      <text space-expand=\"true\" space-fill=\"true\"><label>\"  \"</label></text>
      <button><label>$(gettext 'Install/Update/Delete')</label><action>exit:BUTinstall</action></button>
      <button><label>$(gettext 'Online Information')</label><action>/usr/local/appimage/online-info \"\$TREEaudio\" \"\$TREEdeveloper\" \"\$TREEgames\" \"\$TREEgraphics\" \"\$TREEnetwork\" \"\$TREEoffice\" \"\$TREEproductivity\" \"\$TREEsystem\" \"\$TREEvideo\" \"\$TREEother\" </action></button>
    </hbox>
  </vbox>
</window>
"

RETVALS="$(gtkdialog --center --program=APPIMG_DLG1)"

xRETVALS="$(echo "$RETVALS" | grep -E '^TREE|^EXIT')"
eval "$xRETVALS"
if [ "$EXIT" != "BUTinstall" ];then
 exit
fi

#there could be multiple choices, but let's just do one...
for aAPP in "$TREEaudio" "$TREEdeveloper" "$TREEgames" "$TREEgraphics" "$TREEnetwork" "$TREEoffice" "$TREEproductivity" "$TREEsystem" "$TREEvideo"
do
 if [ "$aAPP" != "" ];then
  break
 fi
done
if [ "$aAPP" == "" ];then
 M1="$(gettext 'No AppImage selected. Aborting.')"
 popup "terminate=ok background=#ff8080 level=top process=wait|<big>${M1}</big>"
 exit 1
fi

#GoldenDict is a continuous build. don't really know how to handle them.
#for now, ask. see github-find-latest-ver script.
#the URL format is: https://github.com/$MEMBER/$PROJECT/
MEMBER=''; PROJECT=''; APPIMG=''
DIRECTDL=''; DIRECTVER='' #20230316
case "${aAPP}" in
 Audacity) MEMBER=audacity; PROJECT=audacity; APPIMG='audacity-linux-VERSION-x64.AppImage'; MENUcat='X-Multimedia-sound'; MENUtop='Multimedia'; MENUname='Audacity audio editor'; ;;
 GitQlient) MEMBER=francescmm; PROJECT=GitQlient; APPIMG='GitQlient-VERSION-x86_64.AppImage'; MENUcat='X-Utility-development'; MENUtop='Utility'; MENUname='GitQlient git client'; ;;
 GoldenDict) MEMBER=Abs62; PROJECT=goldendict; APPIMG='GoldenDict-VERSION-x86_64.AppImage'; MENUcat='X-Document-catalog'; MENUtop='Document'; MENUname='GoldenDict dictionary lookup'; ;;
 PlanetBlupi) MEMBER='blupi-games'; PROJECT='planetblupi-dev'; APPIMG='planetblupi.AppImage'; MENUcat='X-Fun-adventure'; MENUtop='Fun'; MENUname='PlanetBlupi adventure game'; ;;
 PhotoTool) MEMBER='aphototool'; PROJECT='A-Photo-Tool-Libre'; APPIMG='aphototoollibre_VERSION_x86_64.AppImage'; MENUcat='X-Graphic-paint'; MENUtop='Graphic'; MENUname='PhotoTool photo editor'; ;;
 CozyDrive) MEMBER='cozy-labs'; PROJECT='cozy-desktop'; APPIMG='Cozy-Drive-VERSION-x86_64.AppImage'; MENUcat='X-Network-transfer'; MENUtop='Network'; MENUname='CozyDrive sync laptop and desktop PC'; ;;
 Electorrent) MEMBER='Tympanix'; PROJECT='Electorrent'; APPIMG='Electorrent-VERSION.AppImage'; MENUcat='X-Network-transfer'; MENUtop='Network'; MENUname='Electorrent multiprotocol torrent client'; ;;
 ONLYOFFICE) MEMBER='ONLYOFFICE'; PROJECT='appimage-desktopeditors'; APPIMG='DesktopEditors-x86_64.AppImage'; MENUcat='X-Business'; MENUtop='Business'; MENUname='ONLYOFFICE office suite'; ;;
 OneNote) MEMBER='patrikx3'; PROJECT='onenote'; APPIMG='P3X-OneNote-VERSION.AppImage'; MENUcat='X-Personal-organizer'; MENUtop='Personal'; MENUname='OneNote online note taking'; ;;
 ShotCut) MEMBER='mltframework'; PROJECT='shotcut'; APPIMG='shotcut-linux-x86_64-VERSION.AppImage'; MENUcat='X-Multimedia-video'; MENUtop='Multimedia'; MENUname='ShotCut video editor'; ;;
 VidCutter) MEMBER='ozmartian'; PROJECT='vidcutter'; APPIMG='VidCutter-VERSION-x86_64.AppImage'; MENUcat='X-Multimedia-video'; MENUtop='Multimedia'; MENUname='VidCutter video cutter and joiner'; ;;
 Webcamoid) MEMBER='webcamoid'; PROJECT='webcamoid'; APPIMG='webcamoid-portable-linux-VERSION-x86_64.AppImage'; MENUcat='X-Multimedia-video'; MENUtop='Multimedia'; MENUname='Webcamoid webcam suite'; ;;
 AppImagePool) MEMBER='prateekmedia'; PROJECT='appimagepool'; APPIMG='appimagepool-VERSION-x86_64.AppImage'; MENUcat='X-Setup'; MENUtop='Setup'; MENUname='AppImagePool install from AppImageHub'; ;;
 Emacs) MEMBER='probonopd'; PROJECT='Emacs.AppImage'; APPIMG='Emacs-VERSION-x86_64.AppImage'; MENUcat='X-Document-edit'; MENUtop='Document'; MENUname='Emacs text editor'; ;;
 CircuitBlocks) MEMBER='CircuitMess'; PROJECT='CircuitBlocks'; APPIMG='CircuitBlocks-VERSION-Linux.AppImage'; MENUcat='X-Utility-development'; MENUtop='Utility'; MENUname='CircuitBlocks graphical coding for Arduino'; ;;
 Antares) MEMBER='antares-sql'; PROJECT='antares'; APPIMG='Antares-VERSION-linux_x86_64.AppImage'; MENUcat='X-Utility-development'; MENUtop='Utility'; MENUname='Antares SQL client'; ;;
 GDevelop) MEMBER='4ian'; PROJECT='GDevelop'; APPIMG='GDevelop-5-VERSION.AppImage'; MENUcat='X-Utility-development'; MENUtop='Utility'; MENUname='GDevelop no-code game creation'; ;;
 Groot) MEMBER='BehaviorTree'; PROJECT='Groot'; APPIMG='Groot-VERSION-x86_64.AppImage'; MENUcat='X-Graphic-flow'; MENUtop='Graphic'; MENUname='Groot BehaviorTree diagram creator'; ;;
 Guitar) MEMBER='soramimi'; PROJECT='Guitar'; APPIMG='Guitar-VERSION-x86_64.AppImage'; MENUcat='X-Utility-development'; MENUtop='Utility'; MENUname='Guitar GIT GUI client'; ;;
 ImHex) MEMBER='WerWolv'; PROJECT='ImHex'; APPIMG='imhex-VERSION-x86_64.AppImage'; MENUcat='X-Utility-development'; MENUtop='Utility'; MENUname='ImHex hex editor for reverse engineers'; ;;
 KiCad) MEMBER='KarlZeilhofer'; PROJECT='kicad-appimage'; APPIMG='KiCad-VERSION-x86_64.AppImage'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='KiCad schematic-capture and PCB layout'; ;;
 EndlessSky) MEMBER='endless-sky'; PROJECT='endless-sky'; APPIMG='Endless_Sky-vVERSION-x86_64.AppImage'; MENUcat='X-Fun-adventure'; MENUtop='Fun'; MENUname='EndlessSky outer-space adventure'; ;;
 Etcher) MEMBER='balena-io'; PROJECT='etcher'; APPIMG='balenaEtcher-VERSION-x64.AppImage'; MENUcat='X-Setup-installation'; MENUtop='Setup'; MENUname='Etcher write OS to SD and USB drive'; ;;
 Krita) DIRECTDL='https://download.kde.org/stable/krita/5.1.5/krita-5.1.5-x86_64.appimage'; DIRECTVER='5.1.5'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='Krita vector and raster editor'; ;;
 Kdenlive) DIRECTDL='https://download.kde.org/stable/kdenlive/22.12/linux/kdenlive-22.12.3-x86_64.AppImage'; DIRECTVER='22.12.3'; MENUcat='X-Multimedia-video'; MENUtop='Multimedia'; MENUname='Kdenlive video editor'; ;;
 Dust3D) MEMBER='huxingyi'; PROJECT='dust3d'; APPIMG='dust3d-VERSION.AppImage'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='Dust3D 3D modeler'; ;;
 DbGate) MEMBER='dbgate'; PROJECT='dbgate'; APPIMG='dbgate-VERSION-linux_x86_64.AppImage'; MENUcat='X-Business'; MENUtop='Business'; MENUname='DbGate SQL and noSQL client'; ;;
 Figma) MEMBER='Figma-Linux'; PROJECT='figma-linux'; APPIMG='figma-linux_VERSION_linux_x86_64.AppImage'; MENUcat='X-Utility-development'; MENUtop='Utility'; MENUname='Figma User Interface design tool'; ;;
 FreeCAD) MEMBER='FreeCAD'; PROJECT='FreeCAD'; APPIMG='FreeCAD_VERSION-conda-Linux-x86_64-py310.AppImage'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='FreeCAD 3D parametric modeler'; ;;
 Glyphr) MEMBER='glyphr-studio'; PROJECT='Glyphr-Studio-Desktop'; APPIMG='Glyphr.Studio-VERSION.AppImage'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='Glyphr Studio font designer'; ;;
 Heimer) MEMBER='juzzlin'; PROJECT='Heimer'; APPIMG='Heimer-VERSION-x86_64.AppImage'; MENUcat='X-Graphic-flow'; MENUtop='Graphic'; MENUname='Heimer mind mapping tool'; ;;
 Insight) MEMBER='antony-jr'; PROJECT='insight'; APPIMG='Insight-x86_64-pc-linux-gnu-VERSION-x86_64.AppImage'; MENUcat='X-Utility-development'; MENUtop='Utility'; MENUname='Insight frontend for GNU Debugger'; ;;
 KOReader) MEMBER='koreader'; PROJECT='koreader'; APPIMG='koreader-appimage-x86_64-linux-gnu-vVERSION.AppImage'; MENUcat='X-Document-viewer'; MENUtop='Document'; MENUname='KOReader multi-format e-boot reader'; ;;
 KeePassXC) MEMBER='keepassxreboot'; PROJECT='keepassxc'; APPIMG='KeePassXC-VERSION-x86_64.AppImage'; MENUcat='X-Personal-security'; MENUtop='Personal'; MENUname='KeePassXC password manager'; ;;
 LosslessCut) MEMBER='mifi'; PROJECT='lossless-cut'; APPIMG='LosslessCut-linux-x86_64.AppImage'; MENUcat='X-Multimedia-video'; MENUtop='Multimedia'; MENUname='LosslessCut video editor'; ;;
 OpenSCAD) DIRECTDL='https://files.openscad.org/OpenSCAD-2021.01-x86_64.AppImage'; DIRECTVER='2021.01'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='OpenSCAD solid 3D modeller'; ;;
 KoodoReader) MEMBER='troyeguo'; PROJECT='koodo-reader'; APPIMG='Koodo-Reader-VERSION-x86_64.AppImage'; MENUcat='X-Document-viewer'; MENUtop='Document'; MENUname='KoodoReader multi-format e-book reader'; ;;
 DeltaChat) MEMBER='deltachat'; PROJECT='deltachat-desktop'; APPIMG='DeltaChat-VERSION.AppImage'; MENUcat='X-Personal'; MENUtop='Personal'; MENUname='DeltaChat PC and phone messaging app'; ;;
 PDFQuirk) MEMBER='dragotin'; PROJECT='pdfquirk'; APPIMG='PDFQuirk-continuous-x86_64.AppImage'; MENUcat='X-Graphic-utility'; MENUtop='Graphic'; MENUname='PDFQuirk image to PDF converter'; ;;
 #UngoogledChromium) DIRECTDL='https://github.com/clickot/ungoogled-chromium-binaries/releases/download/111.0.5563.65-1/ungoogled-chromium_111.0.5563.65-1.1.AppImage'; DIRECTVER='111.0.5563.65-1'; MENUcat='X-Internet-browser'; MENUtop='Internet'; MENUname='UngoogledChromium browser sans Google Services'; ;;
 UngoogledChromium) MEMBER='clickot'; PROJECT='ungoogled-chromium-binaries'; APPIMG='ungoogled-chromium_VERSION.1.AppImage'; MENUcat='X-Internet-browser'; MENUtop='Internet'; MENUname='UngoogledChromium browser sans Google Services'; ;;
 digiKam) DIRECTDL='https://download.kde.org/stable/digikam/7.10.0/digiKam-7.10.0-x86-64.appimage'; DIRECTVER='7.10.0'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='digiKam professional photo manager'; ;;
 eXeLearning) MEMBER='exelearning'; PROJECT='iteexe'; APPIMG='eXe-VERSION.glibc2.28-x86_64.AppImage'; MENUcat='X-Document'; MENUtop='Document'; MENUname='eXeLearning create education resources'; ;;
 Nanosaur) MEMBER='jorio'; PROJECT='Nanosaur'; APPIMG='Nanosaur-VERSION-linux-x86_64.AppImage'; MENUcat='X-Fun-adventure'; MENUtop='Fun'; MENUname='Nanosaur 3D strategy game'; ;;
 OttoMatic) MEMBER='jorio'; PROJECT='OttoMatic'; APPIMG='OttoMatic-VERSION-linux-x86_64.AppImage'; MENUcat='X-Fun-adventure'; MENUtop='Fun'; MENUname='Nanosaur 3D strategy game'; ;;
 Thunderbird) MEMBER='srevinsaju'; PROJECT='Thunderbird-AppImage'; APPIMG='Thunderbird-VERSION.AppImage'; MENUcat='X-Internet-mailnews'; MENUtop='Internet'; MENUname='Thunderbird mail client'; ;;
 JitsiMeet) MEMBER='jitsi'; PROJECT='jitsi-meet-electron'; APPIMG='jitsi-meet-x86_64.AppImage'; MENUcat='X-Internet-chat'; MENUtop='Internet'; MENUname='JitsiMeet video conferencing'; ;;
 Acreom) MEMBER='Acreom'; PROJECT='releases'; APPIMG='acreom-VERSION.AppImage'; MENUcat='X-Personal'; MENUtop='Personal'; MENUname='Acreom private knowledge base'; ;;
 Zoom) MEMBER='probonopd'; PROJECT='Zoom.AppImage'; APPIMG='Zoom-VERSION-x86_64.AppImage'; MENUcat='VideoConference'; MENUtop='Internet'; MENUname='Zoom video conferencing'; ;;
 OpenShot) DIRECTDL='https://github.com/OpenShot/openshot-qt/releases/download/daily/OpenShot-v3.0.0-daily-11120-f0b44c51-b5bbab66-x86_64.AppImage'; DIRECTVER='3.0.0'; MENUcat='X-Multimedia-video'; MENUtop='Multimedia'; MENUname='OpenShot video editor'; ;;
 Altus) MEMBER='amanharwara'; PROJECT='altus'; APPIMG='Altus-VERSION-x86_64.AppImage'; MENUcat='X-Internet-chat'; MENUtop='Internet'; MENUname='Altus WhatsApp messaging and calls'; ;;
 DBBrowser) MEMBER='sqlitebrowser'; PROJECT='sqlitebrowser'; APPIMG='DB_Browser_for_SQLite-vVERSION-x86_64.AppImage'; MENUcat='X-Business'; MENUtop='Business'; MENUname='DBBrowser create and edit SQLITE databases'; ;;
 Telegram) MEMBER='srevinsaju'; PROJECT='Telegram-AppImage'; APPIMG='Telegram_Desktop-x86_64.AppImage'; MENUcat='X-Internet-chat'; MENUtop='Internet'; MENUname='Telegram messaging'; ;;
 LibreCAD) MEMBER='LibreCAD'; PROJECT='LibreCAD'; APPIMG='LibreCAD-VERSION-x86_64.AppImage'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='LibreCAD 2D CAD'; ;;
 LeoCAD) MEMBER='leozide'; PROJECT='leocad'; APPIMG='LeoCAD-Linux-VERSION-x86_64.AppImage'; MENUcat='X-Graphic'; MENUtop='Graphic'; MENUname='LeoCAD build with lego bricks'; ;;
 CroMagRally) MEMBER='jorio'; PROJECT='CroMagRally'; APPIMG='CroMagRally-VERSION-linux-x86_64.AppImage'; MENUcat='X-Fun-adventure'; MENUtop='Fun'; MENUname='CroMagRally car racing'; ;;
 MyPaint) DIRECTDL='https://github.com/mypaint/mypaint/releases/download/v2.0.1/MyPaint-v2.0.1-alt.AppImage'; DIRECTVER='2.0.1'; MENUcat='X-Graphic-paint'; MENUtop='Graphic'; MENUname='MyPaint paint program'; ;;
 ZZZ) MEMBER=''; PROJECT=''; APPIMG=''; MENUcat=''; MENUtop=''; MENUname=''; ;;
 *)
  exit
 ;;
esac

#test if already installed...
UPDATEflg='no'
if [ -d /mnt/wkg/appimage/${aAPP,,} ];then
 rmdir /mnt/wkg/appimage/${aAPP,,} 2>/dev/null #this will fail if any files.
 if [ $? -ne 0 ];then
  if [ -f /usr/bin/${aAPP,,} ];then
   #already installed.
   SPEC_APPI_ver=''
   if [ -s /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs ];then
    . /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs #has SPEC_APPI_ver
   fi
   #handle the old name, as in easy 5.1.1 and 5.2...
   if [ -s /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.spec ];then
    . /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs #has SPEC_AI_ver
    SPEC_APPI_ver="$SPEC_AI_ver"
   fi
   if [ "$DIRECTDL" != "" -o "$SPEC_APPI_ver" == "" ];then
    UPDATExml="<text><label>$(gettext 'Updating currently not supported for this AppImage.')</label></text>"
   else
    UPDATExml="<text><label>$(gettext 'To probe online if there is a later version and update to it, click the UPDATE button:')</label></text>
        <vbox>
          <button><label>$(gettext 'UPDATE')</label><action>EXIT:update</action></button>
        </vbox>"
   fi
   export APPIMG_DLG6="<window title=\"$(gettext 'AppImage Installer')\">
  <vbox>
    <text use-markup=\"true\">
      <label>\"$(gettext 'Please make a choice for this installed AppImage:')
  <b>${aAPP}</b>
    \"</label></text>
    <frame>
      <hbox>
        ${UPDATExml}
      </hbox>
    </frame>
    <frame>
      <hbox>
        <text><label>$(gettext 'To delete the AppImage installation completely, click the DELETE button:')</label></text>
        <vbox>
          <button><label>$(gettext 'DELETE')</label><action>EXIT:delete</action></button>
        </vbox>
      </hbox>
    </frame>
    <text><label>\"  \"</label></text>
    <hbox>
      <text><label>$(gettext 'Otherwise, click the EXIT button to exit from AppImage Installer:')</label></text>
      <vbox>
        <button><label>$(gettext 'EXIT')</label><action>EXIT:quit</action></button>
      </vbox>
    </hbox>
  </vbox></window>"
   RET2="$(gtkdialog --center --program=APPIMG_DLG6)"
   eval "${RET2}"
   
   case "$EXIT" in
    delete)
     rm -rf /mnt/wkg/appimage/${aAPP,,}
     rm -rf /home/${aAPP,,}
     rm -f /usr/share/applications/${aAPP,,}.desktop
     rm -f /usr/bin/${aAPP,,}
     rm -f /usr/bin/${aAPP,,}.bin
     grep -q "/home/${aAPP,,}/${aAPP,,}" /root/Choices/ROX-Filer/PuppyPin
     if [ $? -eq 0 ];then
      #remove desktop icon...
      echo "<?xml version=\"1.0\"?>
<env:Envelope xmlns:env=\"http://www.w3.org/2001/12/soap-envelope\">
 <env:Body xmlns=\"http://rox.sourceforge.net/SOAP/ROX-Filer\">
  <UnsetIcon>
   <Path>/home/${aAPP,,}/${aAPP,,}</Path>
  </UnsetIcon>
 </env:Body>
</env:Envelope>" | rox -R
     fi
     fixmenus
     jwm -reload
     Md="$(gettext 'AppImage deleted') "
     popup "process=wait terminate=ok background=#80ff80 level=top|<big>${Md}</big>"
     exit
    ;;
    update)
     UPDATEflg='yes'
    ;;
    *)
     exit
    ;;
   esac
  fi
 fi
fi
export UPDATEflg

###new install or update###
if [ "$UPDATEflg" == "yes" ];then
 Mup="$(gettext 'Please confirm that you want to probe online for a later version of this AppImage:')"
else
 Mup="$(gettext 'Please confirm that you want to download and install this AppImage:')"
fi
export APPIMG_DLG5="<window title=\"$(gettext 'AppImage Installer')\">
  <vbox>
   <text use-markup=\"true\"><label>\"${Mup}
  <b>${aAPP}</b>\"</label></text>
  <hbox>
   <button ok></button>
   <button cancel></button>
  </hbox>
  </vbox></window>"
RET1="$(gtkdialog --center --program=APPIMG_DLG5)"
eval "$RET1"
if [ "$EXIT" != "OK" ];then
 exit 0
fi

#need internet connection...
if [ ! -s /tmp/pup_event_backend/network_ ];then
 M5="$(gettext 'An Internet connection is required to download an AppImage.')"
 popup "terminate=ok background=#ff8080 level=top process=wait|<big>${M5}</big>"
 exec appimage
fi

FLG1=0
if [ "$DIRECTDL" != "" ];then
 if [ "$UPDATEflg" == "yes" ];then #precaution.
  exit
 fi
 APPname="${DIRECTDL##*/}"
 APPver="${DIRECTVER}"
 echo -n "$APPname" > /tmp/appimage/APPname
 echo -n "$APPver" > /tmp/appimage/APPver
 echo -n '' > /tmp/appimage/URLtag
 echo -n "$DIRECTDL" > /tmp/appimage/URLdl
 mkdir -p /mnt/wkg/appimage/${aAPP,,}
 cd /mnt/wkg/appimage/${aAPP,,}
 APPnew="${aAPP,,}-${APPver}.AppImage" #this is what renamed to after d/l.
 if [ ! -f "$APPname" ];then #20230317 support manual download.
  if [ ! -f "$APPnew" ];then
   download_file "${DIRECTDL}"
   FLG1=$?
  fi
 fi
else
 /usr/local/appimage/github-find-latest-ver ${MEMBER} ${PROJECT} ${APPIMG}
 #...creates /tmp/appimage/URLtag, APPver, APPname
 if [ $? -ne 0 ];then
  exec appimage
 fi
 URLtag="$(cat /tmp/appimage/URLtag)" #ex: https://github.com/amanharwara/altus/releases/tag/4.8.5
 APPver="$(cat /tmp/appimage/APPver)" #ex: 3.2.5
 APPname="$(cat /tmp/appimage/APPname)" #ex: Zoom-5.14.0.1720.glibc2.17-x86_64.AppImage
 EXIT='download'
 if [ "$UPDATEflg" == "yes" ];then
  export APPIMG_DLG10="<window title=\"$(gettext 'AppImage Installer:') ${aAPP}\">
  <vbox>
    <text use-markup=\"true\">
      <label>\"$(gettext 'This is the currently installed version of the AppImage:')
  <b>${SPEC_APPI_ver}</b>
$(gettext 'This is the latest version found online:')
  <b>${APPver}</b>

$(gettext 'If the latest version is later than the current version, and you want to update, click the UPDATE button. Otherwise, click CANCEL to quit:')\"</label>
    </text>
    <hbox>
     <button>
       <label>$(gettext 'UPDATE')</label>
       <action>EXIT:download</action>
     </button>
     <button>
      <label>$(gettext 'CANCEL')</label>
      <action>EXIT:cancel</action>
     </button>
    </hbox>
  </vbox></window>"
  RET2="$(gtkdialog --center --program=APPIMG_DLG10)"
  eval "$RET2" 
 fi
 
 if [ "$EXIT" == "download" ];then
  if [ "$UPDATEflg" == "yes" ];then
   UPDATEflg='yesyes'
  fi
  #this is what we have to download: ${URLtag}/${APPname}
  mkdir -p /mnt/wkg/appimage/${aAPP,,}
  cd /mnt/wkg/appimage/${aAPP,,}
  echo -n "${URLtag}/${APPname}" > /tmp/appimage/URLdl #for debugging.
  URLdl="$(echo -n "$URLtag" | sed -e 's%/tag/%/download/%')"
  APPnew="${aAPP,,}-${APPver}.AppImage" #this is what renamed to after d/l.
  if [ ! -f "$APPname" ];then #support manual download.
   if [ ! -f "$APPnew" ];then
    download_file ${URLdl}/${APPname}
    FLG1=$?
   fi
  fi
 else
  exit 0
 fi
fi

if [ $FLG1 -ne 0 ];then
 M2="$(gettext 'AppImage download failed. Aborting.')"
 popup "terminate=ok background=#ff8080 level=top process=wait|<big>${M2}</big>"
 if [ -e ./${APPname} ];then
  rm -f ./${APPname}
 fi
 exit 1
fi

#want a consistent name...
APPnew="${aAPP,,}-${APPver}.AppImage"
if [ ! -f $APPnew ];then
 mv -f $APPname  $APPnew
fi
APPname="${APPnew}"

sync
chmod 755 ${APPname}
OFFSET="$(./${APPname} --appimage-offset 2>/dev/null)"
if [ "$OFFSET" == "" ];then
 M3="$(gettext 'The downloaded AppImage seems to be corrupted. Aborting.')"
 popup "terminate=ok background=#ff8080 level=top process=wait|<big>${M3}</big>"
 if [ -e ./${APPname} ];then
  rm -f ./${APPname}
 fi
 exit 2
fi

#open up appimage, need to find out a few things...
mkdir -p /mnt/wkg/appimage/${aAPP,,}/mntpt
busybox mount -o loop,offset=${OFFSET} ${APPname} mntpt
if [ $? -ne 0 ];then
 M4="$(gettext 'The downloaded AppImage seems to be corrupted. Aborting.')"
 popup "terminate=ok background=#ff8080 level=top process=wait|<big>${M4}</big>"
 rm -f ./${APPname}
 exit 3
fi
#extract MimeType from .desktop...
echo -n '' > /tmp/appimage/mimetype
DT1="$(find mntpt mntpt/usr/share/applications -maxdepth 1 -type f -name '*.desktop' 2>/dev/null | tail -n 1)"
if [ "$DT1" ];then
 grep '^MimeType=' ${DT1} > /tmp/appimage/mimetype
fi
sync
busybox umount mntpt
rmdir mntpt

#proceed with install...
if [ "$UPDATEflg" == "yesyes" ];then
 #just redirect symlink to the new appimage...
 cp -a -f /usr/bin/${aAPP,,}.bin /usr/bin/${aAPP,,}.binOLD
 cp -a -f /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specsOLD
 ln -snf /mnt/wkg/appimage/${aAPP,,}/${APPname} /usr/bin/${aAPP,,}.bin
 #also a symlink in same folder as the appimage... no...
 #ln -snf ${APPname} /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.bin
else
 #this symlink is correct, later setup-client will rename to .bin ...
 ln -snf /mnt/wkg/appimage/${aAPP,,}/${APPname} /usr/bin/${aAPP,,}
 #also a symlink in same folder as the appimage... no...
 #ln -snf ${APPname} /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.bin
fi

if [ "${LANG:0:2}" == "en" ];then
 NLSname=''
else
 NLStxt="$(gettext "${MENUname}")"
 NLSname="Name[${LANG:0:2}]=${NLStxt}
"
fi

if [ "$UPDATEflg" != "yesyes" ];then
 echo "[Desktop Entry]
Version=1.0
Type=Application
${NLSname}Name=${MENUname}
GenericName=${aAPP}
Icon=${aAPP,,}.png
Categories=${MENUcat}
Exec=${aAPP,,}" > /usr/share/applications/${aAPP,,}.desktop
 if [ -s /tmp/appimage/mimetype ];then
  cat /tmp/appimage/mimetype >> /usr/share/applications/${aAPP,,}.desktop
 fi

 if [ -d /usr/local/appimage/skeletons/${aAPP,,}/usr ];then
  cp -a -f /usr/local/appimage/skeletons/${aAPP,,}/usr/* /usr/
 fi

 #create /usr/bin/${aAPP,,} script to run as user ${aAPP,,} ...
 setup-client "${aAPP,,}=true"

 if [ -d /usr/local/appimage/skeletons/${aAPP,,}/home/${aAPP,,} ];then
  chown -R ${aAPP,,}:${aAPP,,} /usr/local/appimage/skeletons/${aAPP,,}/home/${aAPP,,}
  cp -a -f /usr/local/appimage/skeletons/${aAPP,,}/home/${aAPP,,}/* /home/${aAPP,,}/ 2>/dev/null
  cp -a -f /usr/local/appimage/skeletons/${aAPP,,}/home/${aAPP,,}/.[a-zA-Z0-9]* /home/${aAPP,,}/ 2>/dev/null
 fi

 #update jwm menu...
 fixmenus
 jwm -reload

 #update the right-click menu...
 build-rox-sendto /usr/share/applications/${aAPP,,}.desktop

 #create a path for optional open/save files for this app
 mkdir -p /files/apps/${aAPP,,}
 chown -R ${aAPP,,}:${aAPP,,} /files/apps/${aAPP,,} #20230318
 #20230319 for extra security...
 chmod 700 /files/apps/${aAPP,,}
fi

#.specs file...
rm -f /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.spec 2>/dev/null #easy 5.1.1 and 5.2
echo -n 'SPEC_APPI_dl=' > /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs
cat /tmp/appimage/URLdl >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs
# ex: https://github.com/webcamoid/webcamoid/releases/tag/9.0.0/webcamoid-portable-linux-9.0.0-x86_64.AppImage
echo '' >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs
echo -n 'SPEC_APPI_tag=' >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs
cat /tmp/appimage/URLtag >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs
# ex: https://github.com/webcamoid/webcamoid/releases/tag/9.0.0
echo '' >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs
echo -n 'SPEC_APPI_name=' >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs
echo "$APPname" >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs #ex: webcamoid-9.0.0.AppImage
echo -n 'SPEC_APPI_ver=' >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs
cat /tmp/appimage/APPver >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs # ex: 9.0.0
echo '' >> /mnt/wkg/appimage/${aAPP,,}/${aAPP,,}.specs

if [ "$UPDATEflg" == "yesyes" ];then
export APPIMG_DLG11="<window title=\"$(gettext 'AppImage Installer: success')\">
  <vbox>
    <text use-markup=\"true\"><label>\"$(gettext 'Success, this is the updated AppImage:')
  <b>${APPname}</b>

$(gettext 'It was downloaded here:')
  /mnt/wkg/appimage/${aAPP,,}
$(gettext 'This symlink points to the new AppImage file:')  
  /usr/bin/${aAPP,,}.bin
$(gettext 'This symlink points to the previous AppImage file:')
  /usr/bin/${aAPP,,}.binOLD

<b>$(gettext 'Notice')</b>
$(gettext 'if you find that the new AppImage does not work, rename the .binOLD symlink to .bin')
\"</label></text>
    <hbox>
     <button ok></button>
    </hbox>
  </vbox>
</window>
"
 gtkdialog --center --program=APPIMG_DLG11
 sync
 exit 0
fi

export APPIMG_DLG2="<window title=\"$(gettext 'AppImage Installer: success')\">
  <vbox>
    <text><label>\"$(gettext 'Success, this AppImage has been installed:')
  ${APPname}
$(gettext 'It was downloaded here:')
  /mnt/wkg/appimage/${aAPP,,}
$(gettext 'This script has been created to run it:')
  /usr/bin/${aAPP,,}
$(gettext 'And a menu entry has been created in this category:')
  ${MENUtop}
$(gettext 'The AppImage will run as this user:')
  ${aAPP,,}
$(gettext 'With user home directory:')
  /home/${aAPP,,}

$(gettext 'This means that the app will only be able to save files in the home directory or anywhere in the /files folder.')
$(gettext 'For your convenience, this folder has been created:')
  /files/apps/${aAPP,,}
$(gettext 'You may, if you wish, configure the app to open/save in this folder.')

$(gettext 'Click the OK button for some final useful information...')\"</label></text>
    <hbox>
     <button ok></button>
    </hbox>
  </vbox>
</window>
"
gtkdialog --center --program=APPIMG_DLG2

export APPIMG_DLG3="<window title=\"$(gettext 'AppImage Installer: notes')\">
  <vbox>
    <frame>
      <text use-markup=\"true\"><label>\"<b>$(gettext 'Security notes')</b>\"</label></text>
      <text use-markup=\"true\"><label>\"$(gettext 'As has been stated in the previous window, the AppImage has been installed to run as a non-root user. In fact, each AppImage runs as its own separate user. This provides isolation, in other words, security.')
$(gettext 'However, you may prefer to run some apps as the root user, a file-manager for example, where you want unfettered access to the entire filesystem, able to open, edit and save anywhere.')\"</label></text>
      <hbox>
       <text><label>$(gettext 'Click for more information:')</label></text>
       <button>
         <label>root</label>
         <action>/usr/local/appimage/notes-security & </action>
       </button>
      </hbox>
    </frame>
    
    <frame>
      <text use-markup=\"true\"><label>\"<b>$(gettext 'Desktop icon')</b>\"</label></text>
      <text use-markup=\"true\"><label>\"$(gettext 'An entry has been created in the menu; however, you can also create a desktop icon.')
$(gettext 'All that you need to do is drag the icon from ROX-Filer, onto the desktop, that is it.')
$(gettext 'You can do it any time in the future, and also can delete the desktop icon by right-click and choose Remove.')\"</label></text>
      <hbox>
       <text><label>$(gettext 'Click for ROX-Filer window:')</label></text>
       <button>
        <label>ROX-Filer</label>
        <action>rox -d /home/${aAPP,,} & </action>
       </button>
      </hbox>
    </frame>
    
    <hbox>
     <button ok></button>
    </hbox>
  </vbox>
</window>
"
gtkdialog --center --program=APPIMG_DLG3

sync
###end###
