#!/bin/sh
#/root/.osmo/config.xml is configured to launch minimized, in systray only.

#20220308 bill reported that if untick start in systray in prefs, it starts
# at each boot.
sed -i -e 's%.*enable_systray.*%    <enable_systray>1</enable_systray>%' /root/.osmo/config.xml

#20220323 baby laptop, restart x, osmo not captured in systray. sleep fixes it...
sleep 2

exec osmo
