#!/bin/sh
#quicksetup can call /usr/sbin/fixinitrd, which will open up and translate the initrd.
#3buildeasydistro will also do it if a non-english build, but we are now only doing
# and en build, with a separate nls sfs.
#note, 3buildeasydistro populates /usr/share/sss/initrd_strings in the initrd.
#want to do translation within the initrd. maybe pass a kernel param "plang=fr"
#base this script on /usr/sbin/fixinitrd (which is a symlink to fixdesk).
#pass in 2-char language to translate to.

LANG1="$1"

if [ ! -f /usr/share/sss/initrd_strings/initrd_strings.${LANG1} ];then
 echo "/usr/share/sss/initrd_strings/initrd_strings.${LANG1} does not exist, cannot translate initrd scripts."
 exit
fi

#sections: general _init _sbin_fixlayers _sbin_fscheck _sbin_rollback _sbin_find-boot-specs _sbin_find-file _ask-country-x _ask-pw-x
for aSECTIONID in $(grep '^\[' /usr/share/sss/initrd_strings/initrd_strings.${LANG1} | tr -d '[' | tr -d ']' | tr '\n' ' ')
do
 [ "$aSECTIONID" = "general" ] && continue
 sPTN="/^\[${aSECTIONID}\]/,/^$/p" #this is a multi-line block find expression.
 #extracts just the relevant block...
 CODEBLOCK="$(sed -n "${sPTN}" /usr/share/sss/initrd_strings/initrd_strings.${LANG1} | sed -e '/^#/d' -e '/%%/d' -e '/^$/d' -e '/^\[/d')"
 [ ! "$CODEBLOCK" ] && continue #precaution.
 #allow any character to be the 'marker' for / in the section-id...
 MARKERCHAR="${aSECTIONID:0:1}"
 TARGETFILE="$(echo -n "${aSECTIONID}" | tr "${MARKERCHAR}" '/')" #ex: /sbin/fscheck
 [ ! -e "${TARGETFILE}" ] && continue #precaution.
 if [ ! -f ${TARGETFILE}.en ];then
  cp -a -f ${TARGETFILE} ${TARGETFILE}.en
 fi
 echo "  Translating ${TARGETFILE}.en to '${LANG1}'..."
 echo "$CODEBLOCK" > /tmp/fixdesk-translationblock
 #ensure that all [ ] are escaped, plus escape '.' chars...
 sed -i -e 's%\[%\\[%g' -e 's$\]$\\]$g' -e 's%\\\\\[%\\[%g' -e 's%\\\\\]%\\]%g' /tmp/fixdesk-translationblock
 sed -i -e 's%\.%\\.%g' -e 's%\\\\\.%\\.%g' /tmp/fixdesk-translationblock #note: 2nd ptn gets rid of prior escape char, so there remains just one.
 sed -f /tmp/fixdesk-translationblock "${TARGETFILE}.en" > ${TARGETFILE}.${LANG1}
 ln -snf ${TARGETFILE##*/}.${LANG1} ${TARGETFILE}
done
###end###
