#!/bin/ash
#this is to run X apps in the initrd.

/usr/bin/xsetroot -cursor_name top_left_arrow

#20230123 20230124
if [ "$fbX" == "800" ];then
 /usr/bin/xloadimage -onroot -quiet -fullscreen /logo800x600.png
else
 /usr/bin/xloadimage -onroot -quiet -fullscreen /logo1920x1440.png
fi

if [ $2 ];then
 exec /${1} ${2}
else
 exec /${1}
fi
