#!/bin/ash
#this is to run X apps in the initrd.

/usr/bin/xsetroot -cursor_name top_left_arrow

#20230123
/usr/bin/xloadimage -onroot -quiet -fullscreen -display :0 logo1920x1440new.png

if [ $2 ];then
 exec /${1} ${2}
else
 exec /${1}
fi
