#!/bin/bash

export TEXTDOMAIN=flatpaks
export TEXTDOMAINDIR=/usr/share/locale
export OUTPUT_CHARSET=UTF-8

ENTRIESaudio="
<item icon-name=\"audacity\">Audacity|${FLGaudacity}|$(gettext 'A free, easy-to-use, multi-track audio editor and recorder')</item>
<item icon-name=\"cozy\">Cozy|${FLGcozy}|$(gettext 'Audio book player')</item>
<item icon-name=\"musicblocks\">MusicBlocks|${FLGmusicblocks}|$(gettext 'Graphical music concepts discovery')</item>
<item icon-name=\"spotify\">Spotify|${FLGspotify}|$(gettext 'Online music streaming service')</item>
<item icon-name=\"tuner\">Tuner|${FLGtuner}|$(gettext 'Listen to Internet radio stations')</item>
"
echo "$ENTRIESaudio" > /tmp/flatpak/ENTRIESaudio

ENTRIESdeveloper="
<item icon-name=\"androidstudio\">AndroidStudio|${FLGandroidstudio}|$(gettext 'IDE for Android app development')</item>
<item icon-name=\"cambalache\">Cambalache|${FLGcambalache}|$(gettext 'GTK3 and GTK4 interface designer')</item>
<item icon-name=\"diylc\">DIYLC|${FLGdiylc}|$(gettext 'Electrical and electronic circuit board layout designer')</item>
<item icon-name=\"gdevelop\">GDevelop|${FLGgdevelop}|$(gettext 'No-code game development')</item>
<item icon-name=\"purrdata\">PurrData|${FLGpurrdata}|$(gettext 'Visual programming environment')</item>
<item icon-name=\"scratch\">Scratch|${FLGscratch}|$(gettext 'Simple GUI app creator')</item>
<item icon-name=\"smartgit\">SmartGit|${FLGsmartgit}|$(gettext 'Git and SVN client. No.1 rating at slant.co')</item>
<item icon-name=\"vscode\">VSCode|${FLGvscode}|$(gettext 'Visual Studio Code editor')</item>
"
echo "$ENTRIESdeveloper" > /tmp/flatpak/ENTRIESdeveloper

ENTRIESgames="
<item icon-name=\"frogatto\">Frogatto|${FLGfrogatto}|$(gettext '2D adventure game')</item>
<item icon-name=\"leocad\">LeoCAD|${FLGleocad}|$(gettext '3D build with Lego bricks')</item>
<item icon-name=\"ppsspp\">PPSSPP|${FLGppsspp}|$(gettext 'PlayStation PSP emulator')</item>
<item icon-name=\"spacecadetpinball\">SpaceCadetPinball|${FLGspacecadetpinball}|$(gettext '3D pinball game')</item>
"
echo "$ENTRIESgames" > /tmp/flatpak/ENTRIESgames

ENTRIESgraphics="
<item icon-name=\"blender\">Blender|${FLGblender}|$(gettext '3D image creation')</item>
<item icon-name=\"diylc\">DIYLC|${FLGdiylc}|$(gettext 'Circuit board layout creator')</item>
<item icon-name=\"freecad\">FreeCAD|${FLGfreecad}|$(gettext '3D parametric Computer Aided Drafting')</item>
<item icon-name=\"gimagereader\">gImageReader|${FLGgimagereader}|$(gettext 'GUI for tesseract Optical Character Recognition (OCR)')</item>
<item icon-name=\"krita\">Krita|${FLGkrita}|$(gettext 'Vector and raster painting program')</item>
<item icon-name=\"librecad\">LibreCAD|${FLGlibrecad}|$(gettext '2D Computer Aided Drafting')</item>
<item icon-name=\"librepcb\">LibrePCB|${FLGlibrepcb}|$(gettext 'Electronic printed circuit board design')</item>
<item icon-name=\"opentoonz\">OpenToonz|${FLGopentoonz}|$(gettext '2D animation')</item>
<item icon-name=\"pencil2d\">Pencil2D|${FLGpencil2d}|$(gettext 'Vector and raster 2D animation')</item>
<item icon-name=\"qelectrotech\">QElectroTech|${FLGqelectrotech}|$(gettext 'Electrical circuit design')</item>
<item icon-name=\"sweethome\">SweetHome|${FLGsweethome}|$(gettext '3D home furniture layout')</item>
"
echo "$ENTRIESgraphics" > /tmp/flatpak/ENTRIESgraphics

#20240622 rem as have in menu:
# <item icon-name=\"chromium\">UnGoogled|${FLGungoogled}|$(gettext 'Un-Googled Chromium web browser')</item>
# <item icon-name=\"chrome\">Chrome|${FLGchrome}|$(gettext 'Web browser by Google')</item>
ENTRIESnetwork="
<item icon-name=\"brave\">Brave|${FLGbrave}|$(gettext 'Secure web browser')</item>
<item icon-name=\"discord\">Discord|${FLGdiscord}|$(gettext 'Message and video sharing')</item>
<item icon-name=\"fragments\">Fragments|${FLGfragments}|$(gettext 'A BitTorrent client')</item>
<item icon-name=\"jitsimeet\">JitsiMeet|${FLGjitsimeet}|$(gettext 'Video conferencing')</item>
<item icon-name=\"signal\">Signal|${FLGsignal}|$(gettext 'Private messaging')</item>
<item icon-name=\"skype\">Skype|${FLGskype}|$(gettext 'Audio and video calls')</item>
<item icon-name=\"teams\">Teams|${FLGteams}|$(gettext 'Microsoft Teams client')</item>
<item icon-name=\"telegram\">Telegram|${FLGtelegram}|$(gettext 'Secure message and video sharing')</item>
<item icon-name=\"tor\">Teams|${FLGtor}|$(gettext 'Secure web browser')</item>
<item icon-name=\"whatsapp\">WhatsApp|${FLGwhatsapp}|$(gettext 'Messaging and calls')</item>
<item icon-name=\"zoom\">Zoom|${FLGzoom}|$(gettext 'Video conferencing')</item>
"
echo "$ENTRIESnetwork" > /tmp/flatpak/ENTRIESnetwork

ENTRIESoffice="
<item icon-name=\"betterbird\">Betterbird|${FLGbetterbird}|$(gettext 'Fork of Mozilla Thunderbird mail client')</item>
<item icon-name=\"calibre\">Calibre|${FLGcalibre}|$(gettext 'E-book reader')</item>
<item icon-name=\"dbbrowser\">DBBrowser|${FLGdbbrowser}|$(gettext 'Create and edit SQLITE databases')</item>
<item icon-name=\"gnucash\">GnuCash|${FLGgnucash}|$(gettext 'Personal and small-business accounting')</item>
<item icon-name=\"okular\">Okular|${FLGokular}|$(gettext 'Universal document viewer')</item>
<item icon-name=\"thunderbird\">Thunderbird|${FLGthunderbird}|$(gettext 'Mail and newsgroup client')</item>
"
echo "$ENTRIESoffice" > /tmp/flatpak/ENTRIESoffice

#20230621 removed:
#<item icon-name=\"keepassxc\">KeePassXC|${FLGkeepassxc}|$(gettext 'Password manager')</item>
#20230707 badly broke:
#<item icon-name=\"minder\">Minder|${FLGminder}|$(gettext 'Mind-mapping ideas visualization tool')</item>
ENTRIESproductivity="
<item icon-name=\"authpass\">AuthPass|${FLGauthpass}|$(gettext 'Password manager')</item>
<item icon-name=\"bitwarden\">Bitwarden|${FLGbitwarden}|$(gettext 'Password manager')</item>
<item icon-name=\"cherrytree\">CherryTree|${FLGcherrytree}|$(gettext 'Hierarchical note-taking and personal database')</item>
<item icon-name=\"goldendict\">GoldenDict|${FLGgoldendict}|$(gettext 'Dictionary lookup program')</item>
<item icon-name=\"identity\">Identity|${FLGidentity}|$(gettext 'Compare multiple versions of an image or video')</item>
<item icon-name=\"trilium\">Trilium|${FLGtrilium}|$(gettext 'Hierarchical note-taking and personal database')</item>
"
echo "$ENTRIESproductivity" > /tmp/flatpak/ENTRIESproductivity

ENTRIESsystem="
<item icon-name=\"dosbox\">DOSBox|${FLGdosbox}|$(gettext 'DOS emulator')</item>
<item icon-name=\"ktorrent\">KTorrent|${FLGktorrent}|$(gettext 'KDE BitTorrent client')</item>
"
echo "$ENTRIESsystem" > /tmp/flatpak/ENTRIESsystem

#removed, coz have native oe app...
#<item icon-name=\"obs\">OBS|${FLGobs}|$(gettext 'OBS-Studio video capture, recording and live streaming')</item>
ENTRIESvideo="
<item icon-name=\"kdenlive\">Kdenlive|${FLGkdenlive}|$(gettext 'Nonlinear video editor')</item>
<item icon-name=\"kodi\">Kodi|${FLGkodi}|$(gettext 'Multimedia player')</item>
<item icon-name=\"openshot\">OpenShot|${FLGopenshot}|$(gettext 'Easy and powerful video editor')</item>
<item icon-name=\"shotcut\">ShotCut|${FLGshotcut}|$(gettext 'Video editor')</item>
<item icon-name=\"stremio\">Stremio|${FLGstremio}|$(gettext 'Streaming media player')</item>
"
echo "$ENTRIESvideo" > /tmp/flatpak/ENTRIESvideo

ENTRIESother="
<item icon-name=\"bottles\">Bottles|${FLGbottles}|$(gettext 'Run Windows apps')</item>
<item icon-name=\"gramps\">Gramps|${FLGgramps}|$(gettext 'Genealogy program')</item>
<item icon-name=\"maps\">Maps|${FLGmaps}|$(gettext 'OpenStreetMaps map of the world')</item>
<item icon-name=\"organicmaps\">OrganicMaps|${FLGorganicmaps}|$(gettext 'Offline maps for travellers, hikers and cyclists')</item>
<item icon-name=\"qgis\">QGIS|${FLGqgis}|$(gettext 'Open source Geographic Information System')</item>
"
echo "$ENTRIESother" > /tmp/flatpak/ENTRIESother

#20230510 custom...
for aCUST in $(find /usr/local/flapi/custom -mindepth 1 -maxdepth 1 -type f | tr '\n' ' ')
do
 aNAME="${aCUST##*/}" #ex: goldendict
 [ "$aNAME" == "template" ] && continue
 . ${aCUST}
 aDESC="$(gettext "${cAPPdesc}")" #ex: Dictionary lookup program
 aFLG=FLG${cAPPname,,} #bash variable indirection.
 echo "<item icon-name=\"${cAPPname,,}\">${cAPPname}|${!aFLG}|${aDESC}</item>" >> /tmp/flatpak/ENTRIES${cCATEGORY}
done
###end###
