#!/bin/bash
#called from ppm (/usr/local/petget/configure.sh) when do pkg db update.

export LANG=C

apt-get update 2>/dev/null

#convert dpkg to /root/.packages/Packages-debian-* pup-format...
/usr/local/debget/sync-dpkg2pupdb
sync

###end###
