#!/bin/sh
#called from apt-setup
#/var/lib/dpkg/status has installed pkgs, derived from woof-installed-packages and user-installed-packages
#however, the deps of these packages may not all be shown as installed.
#20220908 write to 'available' file, instead of 'status0'.
#20220911 fix available0 missing blank lines.

#ref: https://manpages.ubuntu.com/manpages/bionic/man8/apt-mark.8.html
#may need to prevent apt/dpkg from installing or updating some packages.
# ex: # apt-mark hold systemd
# writes to /var/lib/dpkg/available, /var/lib/dpkg/status
# ...entry in 'available' will prevent systemd from being installed.
#    'status' has new entry, with "Status: hold ok not-installed"

export LANG=C
. /var/local/pkgget/deb_compat_specs #DEBDISTRO, DEBVERSION, DEBARCH
mkdir -p /tmp/debget

MISSINGDEPS="$(grep '^Depends: ' /var/lib/dpkg/status | cut -f 2- -d ':' | sed -r -e 's%\([^,]*%%g' | tr -d ',' | tr '\n' ' ' | tr -s ' ' | tr ' ' '\n' | sort -u)"

echo -n '' > /tmp/debget/available0
echo -n '' > /var/lib/dpkg/available
for aMISS in ${MISSINGDEPS}
do
 #check not already listed...
 grep -q "^Package: ${aMISS}$" /var/lib/dpkg/status
 if [ $? -eq 0 ];then
  continue
 fi
 aPARA="$(sed -n "/^Package: ${aMISS}$/,/^$/p" /var/lib/apt/lists/deb*_Packages)"
 if [ "$aPARA" ];then
  #echo "$aPARA" >> /tmp/debget/status0
  #touch /var/lib/dpkg/info/${aMISS}:${DEBARCH}.conffiles
  #touch /var/lib/dpkg/info/${aMISS}:${DEBARCH}.list
  #touch /var/lib/dpkg/info/${aMISS}:${DEBARCH}.md5sums
  #touch /var/lib/dpkg/info/${aMISS}:${DEBARCH}.shlibs
  #touch /var/lib/dpkg/info/${aMISS}:${DEBARCH}.symbols
  #touch /var/lib/dpkg/info/${aMISS}:${DEBARCH}.triggers
  #no, just write to 'available'...
  echo "$aPARA" >> /tmp/debget/available0
  echo '' >> /tmp/debget/available0 #20220911
 fi
done

#20220908 now write to 'available'...
#some of these fields not allowed in 'status' file...
# we want a Status entry...
sed -i -e 's%^Filename: .*%Status: hold ok not-installed%' /tmp/debget/available0
sed -i '/^Size: /d' /tmp/debget/available0
sed -i '/^MD5sum: /d' /tmp/debget/available0
sed -i '/^SHA256: /d' /tmp/debget/available0
sed -i '/^Pre-Depends: /d' /tmp/debget/available0
sed -i '/^Depends: /d' /tmp/debget/available0
sed -i '/^Suggests: /d' /tmp/debget/available0
sed -i '/^Description-md5: /d' /tmp/debget/available0
sed -i '/^Tag: /d' /tmp/debget/available0
sed -i '/^ /d' /tmp/debget/available0

#fix para blank lines...
sed -i -e 's%Package: %\nPackage: %' /tmp/debget/available0
#remove 1st line in file, which is now blank...
sed -i '1d' /tmp/debget/available0

# -s suppresses duplicate blank lines...
cat -s /tmp/debget/available0 > /var/lib/dpkg/available
sed -i '/^Status: /d' /var/lib/dpkg/available
#need a blank line at end of file...
echo '' >> /var/lib/dpkg/available

cat -s /tmp/debget/available0 >> /var/lib/dpkg/status
echo '' >> /var/lib/dpkg/status
sync

###end###
