#!/bin/bash
#call from ppm (/usr/local/petget/removepreview.sh) when uninstall a pkg
#/tmp/debget/pup-db-single-rem is pkg pup-format-db that has been removed.

export LANG=C

/usr/local/debget/pupdb2debdb-single.sh
#...writes to /tmp/debget/working/fnd-deb-paras
#try hack, see if can fool dpkg and apt...
grep -q '^P' /tmp/debget/working/fnd-deb-paras
if [ $? -eq 0 ];then
 PUPnameonly="$(cut -f 2 -d '|' /tmp/debget/pup-db-single-rem)"
 PUPversion="$(cut -f 3 -d '|' /tmp/debget/pup-db-single-rem)"
 #need to do reverse of this...
 # cat /tmp/debget/working/fnd-deb-paras >> /var/lib/dpkg/status
 for aNAME in $(grep '^Package: ' /tmp/debget/working/fnd-deb-paras | cut -f 2 -d ' ' | tr '\n' ' ')
 do
  #remove paragraph from /var/lib/dpkg/status ...
  sed -i -n '/^Package: '"${aNAME}"'$/,/^$/d' /var/lib/dpkg/status
  #extract paragraph...
  sed -n '/^Package: '"${aNAME}"'$/,/^$/p' /tmp/debget/working/fnd-deb-paras > /tmp/debget/extracted-para-rem
  #if a library, only record to dpkg as installed if version <= $PUPversion
  grep -q '^Section: libs$' /tmp/debget/extracted-para-rem
  if [ $? -eq 0 ];then
   DEBversion="$(grep '^Version: ' /tmp/debget/extracted-para-rem | cut -f 2 -d ' ' | cut -f 2 -d ':')"
   vercmp ${DEBversion} gt ${PUPversion}
   if [ $? -eq 0 ];then
    #do not show in dpkg as being installed. hence any pkg the dpkg installs,
    # that has this dep, it will be installed from deb repo.
    #note, this section of code is in sync-new2dpkg, but the logic also applies when remove.
    continue
   fi
  fi
  #rm -f /var/lib/dpkg/info/${aNAME}.list
  #rm -f /var/lib/dpkg/info/${aNAME}.conffiles
  #rm -f /var/lib/dpkg/info/${aNAME}.md5sums
  rm -f /var/lib/dpkg/info/${aNAME}:${DEBARCH}.*
 done
fi

###end###
