#!/bin/ash
#current path must be at /mnt/wkg/data/woofv

[ ! -d rootfs ] && exit 1
[ ! -d dl-xbps ] && exit 2

busybox mount -o bind /proc rootfs/proc
busybox mount -o bind /sys rootfs/sys
busybox mount -o bind /dev rootfs/dev
busybox mount -o bind /dev/pts rootfs/dev/pts
busybox mount -o bind /dev/shm rootfs/dev/shm

busybox mount -o bind dl-xbps rootfs/var/cache/xbps

#for internet access...
cp -f /etc/resolv.conf rootfs/etc/resolv.conf

chroot rootfs ${@}

sync
busybox umount rootfs/var/cache/xbps
busybox umount rootfs/dev/shm
busybox umount rootfs/dev/pts
busybox umount rootfs/dev
busybox umount rootfs/sys
busybox umount rootfs/proc
