#!/bin/bash
#pass in path to pkgdb-0.38.plist
# (normally that will be /var/db/xbps/pkgdb-0.38.plist)

DB1="$1"
E2='/mnt/wkg/data'
mkdir -p ${E2}/update
rm -rf ${E2}/update/extracted-user-installed 2>/dev/null
mkdir ${E2}/update/extracted-user-installed
rm -rf ${E2}/update/extracted-user-files 2>/dev/null
mkdir ${E2}/update/extracted-user-files

if [ ! -s /root/.packages/user-installed-packages ];then
 exit
fi

#get list of user-installed pkgs...
cut -f 2 -d '|' /root/.packages/user-installed-packages > ${E2}/update/user-installed-names

#break each pkg into a paragraph...
sed -e 's%^	<key>%\n	<key>%' ${DB1} > ${E2}/update/pkgdb-paras

#extract all user-installed db entries from plist...
NAME=''
#note IFS= is required to retain leading tab chars...
while IFS= read -r aL
do
 if [ "$aL" == "" ];then
  read aL
  NAME="$(cut -f 2 -d '>' <<<${aL} | cut -f 1 -d '<')" #ex: <key>libwv</key>
  grep -q -x -f ${E2}/update/user-installed-names <<<${NAME}
  if [ $? -ne 0 ];then
   NAME=''
   continue
  fi
  echo -n "	" > ${E2}/update/extracted-user-installed/${NAME}
 fi
 if [ -z "$NAME" ];then
  continue
 fi
 echo -n '.'
 echo "${aL}" >> ${E2}/update/extracted-user-installed/${NAME}
done <${E2}/update/pkgdb-paras
echo

#there are hidden files, that list the files in each package...
for aL in $(cat ${E2}/update/user-installed-names)
do
 if [ -z "$aL" ];then
  continue
 fi
 if [ -f ${DB1%/*}/.${aL}-files.plist ];then
  cp -a ${DB1%/*}/.${aL}-files.plist ${E2}/update/extracted-user-files/
 fi
done
###end###
