#!/bin/sh
# application_x-sqlite3
# Requires the Mozilla sqlitemanager plugin from
# https://addons.mozilla.org/en-US/firefox/addon/sqlite-manager/
# or sqlitemanager-*.pet.
####
exec sqlitemanager.sh "$1"
