#!/bin/sh
#3buildeasydistro will use the downloaded file.

#curl -L https://youtube-dl.org/downloads/latest/youtube-dl -o ./youtube-dlNEW
#curl -L https://yt-dl.org/downloads/latest/youtube-dl -o ./youtube-dlNEW
#20230223 this site creates nightly downloads from latest commit at official site...
#curl -L https://github.com/ytdl-patched/youtube-dl/releases/latest/download/youtube-dl -o ./youtube-dlNEW
#...20240406 last commit is 10 months ago!

#20240723 ***NOTICE***
#in future might have to get from here
#https://github.com/ytdl-org/ytdl-nightly

curl -L https://github.com/Dexus-Forks/youtube-dl/releases/latest/download/youtube-dl -o ./youtube-dlNEW
if [ $? -ne 0 ];then
 rm -f youtube-dlNEW 2>/dev/null
fi
if [ ! -s youtube-dlNEW ];then
 rm -f youtube-dlNEW 2>/dev/null
fi
if [ -e youtube-dlNEW ];then
 mv -f youtube-dlNEW youtube-dl
 chmod 755 youtube-dl
fi

###end###
