#!/bin/sh

export WAITENDPINSTALL='no'
export WAITHUNSPELLPET='no'
export DODEPSCHECK='no'
export SEAMONKEYASCLIENT='yes' #20210913 ask, no, yes (default ask)
export ASKEXTRATRANSPKGS='yes'
export ASKREPACKJAR='no'
export ASKDISABLEAPPLETS='no'
export ASKEASYIDFILE='no'
export ASKINBUILTINITRD='no'
export RUNCHOOSETHEMES='no'
export ASKDLSMLANGPACK='no'
export DEFAULTPAorPW='pa' #20211103 pa, pw, ask (default ask).
export FIREFOXASCLIENT='yes' #2021108 ask, no, yes (default ask)
export CLAWSASCLIENT='yes' #2021212 ask, no, yes (default ask)
export CHROMIUMASCLIENT='yes' #2021213 ask, no, yes (default ask)
export HEXCHATASCLIENT='yes' #20220606

./3buildeasydistro
sync
###end###
