#!/bin/sh

DEPS="$(cut -f 9 -d '|' woof-installed-packages devx-only-installed-packages | tr ',' '\n' | cut -c 2- | sort -u | tr '\n' ' ')"

for aDEP in $DEPS
do
 grep -q -F "|${aDEP}|" woof-installed-packages devx-only-installed-packages
 if [ $? -ne 0 ];then
  echo "MISSING: ${aDEP}"
 fi
done
