#!/bin/bash
#(c) Copyright Barry Kauler, Nov. 2016, barryk.org. Licence GPL3 (ref: /usr/share/doc/legal)
#audio out selection, called from simplevp. chosen player is passed in.
#requires bash, as uses "!" operator for indirection.

PLAYER="$1" #at startup will be $CLI_PLAYER, via combobox will be $NEW_CLI. ex: VLC

BOOT_BOARD='pc'
[ -f /etc/rc.d/BOOTCONSTRAINED ] && . /etc/rc.d/BOOTCONSTRAINED #has BOOT_BOARD, values "raspi", "odroidx"
. /var/local/simplevp/settings #has CLI_PLAYER, CHOICES_AOUT*, AUDIO_OUT*

PTR="AUDIO_OUT_${BOOT_BOARD}_${PLAYER}"
DEF_AOUT="${!PTR}"
PTR="CHOICES_AOUT_${BOOT_BOARD}_${PLAYER}"
CHOICES="${!PTR}"
#although comboboxtext tag allows <default> tag, does not work when dynamic refresh,
#so order list with $DEF_VOUT first...
ITEMS="$(echo -n "$CHOICES" | tr ' ' '\n' | grep -v "^${DEF_AOUT}$")"
echo "${DEF_AOUT}
${ITEMS}" > /tmp/simplevp/aout_items
echo -n "$DEF_AOUT" > /tmp/simplevp/def_aout

###END###
